version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries: "*"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    target-branch: "feature/corese-next"