package fr.inria.corese.core.next.query.impl.parser;

import fr.inria.corese.core.next.data.impl.common.vocabulary.RDF;
import fr.inria.corese.core.next.data.impl.io.common.IOConstants;
import fr.inria.corese.core.next.impl.parser.antlr.SparqlParser;
import fr.inria.corese.core.next.query.api.exception.QueryEvaluationException;
import fr.inria.corese.core.next.query.api.exception.QuerySyntaxException;
import fr.inria.corese.core.next.query.api.exception.QueryValidationException;
import fr.inria.corese.core.next.query.impl.parser.semantic.support.VariableScopeAnalyzer;
import fr.inria.corese.core.next.query.impl.sparql.ast.*;
import fr.inria.corese.core.next.query.impl.sparql.ast.path.PathAst;
import fr.inria.corese.core.next.query.impl.sparql.ast.path.PredicatePathAst;

import java.util.*;

/**
 * Root class of the query builders.
 * Offers functions to create ASTs and convert contexts from the ANTLR parser to ASTs
 */
public abstract class SparqlAstBuilder {

    private static final String GENERATED_BLANK_NODE_PREFIX = IOConstants.BLANK_NODE_PREFIX + "b";

    /** Parser options shared by syntax and AST construction. */
    protected final SparqlParserOptions options;

    /**
     * Effective base URI after prologue (parser options, then possibly {@code BASE}).
     */
    protected String baseUri;

    /**
     * Prefix declarations in source order (including redeclarations).
     */
    protected final List<PrefixDeclarationAst> prefixDeclarations = new ArrayList<>();

    /**
     * Dataset clause (FROM/FROM NAMED)
     */
    protected final Set<IriAst> datasetDefaultGraphs = new LinkedHashSet<>();
    protected final Set<IriAst> datasetNamedGraphs = new LinkedHashSet<>();

    /**
     * Used for BIND scope checks (variable must not already be visible in the same group).
     */
    protected final VariableScopeAnalyzer variableScopeAnalyzer = new VariableScopeAnalyzer();

    /** Stack of graph-pattern groups currently being built. */
    protected final Deque<List<PatternAst>> groupStack = new ArrayDeque<>();

    /**
     * Stack of current BGP triples (TriplesBlock). Nested blocks are rare but stack keeps it safe.
     */
    protected final Deque<List<TriplePatternAst>> bgpStack = new ArrayDeque<>();

    /**
     * Counter for anonymous blank nodes created while expanding {@code [ ... ]} and {@code ( ... )} subjects.
     */
    private int anonymousBlankNodeCounter;

    /**
     * Blank node labels already present in the query or generated by this builder.
     */
    private final Set<String> blankNodeLabels = new HashSet<>();

    /**
     * Stack of currently open SELECT operations (top-level SELECT and nested SELECT subqueries).
     */
    protected final Deque<SelectFrame> selectStack = new ArrayDeque<>();

    /**
     * When true, the next {@link #enterGroup()} opens the {@code groupGraphPattern} of a
     * {@code whereClause} for the innermost active {@link SparqlQueryAstBuilder.SelectFrame}. On matching
     * {@link #exitGroup()}, that group is stored as {@link SparqlQueryAstBuilder.SelectFrame#whereClause} instead of
     * being appended to the enclosing graph group (required when outer WHERE groups are still open,
     * e.g. subqueries {@code { SELECT ... WHERE { ... }}}).
     */
    protected boolean selectWhereGroupFollows;

    /**
     * Depths ({@code groupStack.size()} after push) of SELECT WHERE groups still to be closed,
     * innermost last. Matched on {@link #exitGroup()} while {@link #hasCurrentSelect()}.
     */
    protected final Deque<Integer> selectWhereGroupDepths = new ArrayDeque<>();

    /**
     * At enterOptional(), we push groupStack.size(). At exitGroup(), if groupStack.size() equals peek, we wrap in OptionalAst.
     */
    protected final Deque<Integer> optionalGroupDepths = new ArrayDeque<>();

    /**
     * At enterMinus(), we push groupStack.size(). At exitGroup(), if groupStack.size() equals peek, we wrap in MinusAst.
     */
    protected final Deque<Integer> minusGroupDepths = new ArrayDeque<>();

    /**
     * At enterExistsFunc()/enterNotExistsFunc(), we push groupStack.size().
     * At exitGroup(), if groupStack.size() equals peek, we capture in capturedExistsPattern.
     */
    protected final Deque<Integer> existsGroupDepths = new ArrayDeque<>();

    /**
     * Stack of UNION branch lists currently being collected.
     */
    protected final Deque<List<GroupGraphPatternAst>> unionStack = new ArrayDeque<>();

    /**
     * Holds the endpoint and silent flag for each active SERVICE scope.
     * Pushed on enterService(), matched (by groupDepth) in exitGroup() to produce a ServiceAst.
     *
     * @param groupDepth the {@code groupStack.size()} at the time {@link #enterService} was called,
     *                   i.e. the depth before the SERVICE body's {@link SparqlQueryAstBuilder#enterGroup()} is invoked.
     *                   After {@link SparqlQueryAstBuilder#exitGroup()} pops the service body the stack returns to this
     *                   depth, which is used as the signal to wrap the group in a
     *                   {@link ServiceAst}.
     * @param endpoint   the remote service endpoint (IRI or variable)
     * @param silent     whether the {@code SILENT} keyword was present
     */
    protected record ServiceEntry(int groupDepth, TermAst endpoint, boolean silent) {}

    /**
     * Stack of pending SERVICE entries, innermost last.
     * At enterService(), we push a ServiceEntry with the current groupStack depth.
     * At exitGroup(), if groupStack.size() equals the top entry's groupDepth, we wrap the closed
     * group in a ServiceAst.
     */
    protected final Deque<ServiceEntry> serviceStack = new ArrayDeque<>();

    /*
     * having conditions
     */
    protected final List<TermAst> havingConditions = new ArrayList<>();

    /**
     * Top-level WHERE clause, set when the root group is closed in exitGroup().
     */
    protected GroupGraphPatternAst whereClause;

    /**
     * Captured GroupGraphPattern for the last closed EXISTS/NOT EXISTS block.
     * Consumed by termFromBuiltInCall via popCapturedExistsPattern().
     */
    protected final Deque<GroupGraphPatternAst> capturedExistsStack = new ArrayDeque<>();

    /**
     * Stateless term-building helpers.
     */
    protected final SparqlTermBuilder terms;

    /** Property-path building helpers. */
    protected final SparqlPathBuilder paths;

    /** Expression and constraint building helpers. */
    protected final SparqlExpressionBuilder expressions;

    protected SparqlAstBuilder(SparqlParserOptions options) {
        this.options = options;
        this.baseUri = options.getBaseIRI();
        this.terms = new SparqlTermBuilder(options, this::termFromBlankNode);
        this.paths = new SparqlPathBuilder(this.terms);
        this.expressions = new SparqlExpressionBuilder(this.terms, this::popCapturedExistsPattern);
    }

    public void reserveBlankNodeLabels(Collection<String> labels) {
        blankNodeLabels.addAll(Objects.requireNonNull(labels, "labels"));
    }

    // --- Construction entry points (called by listener) ---

    public void setBaseUri(String uri) {
        if(this.baseUri != null && !this.baseUri.equals(options.getBaseIRI())) {
            throw new QuerySyntaxException("Base URI already set, multiple BASE declarations are forbidden.");
        }
        this.baseUri = uri;
    }

    public void addPrefix(String prefix, String uri) {
        PrefixDeclarationAst declarationAst = new PrefixDeclarationAst(prefix, new IriAst(uri));
        if(this.prefixDeclarations.stream().anyMatch(declaration ->
                Objects.equals(declaration.prefix(), declarationAst.prefix())
        )) {
            throw new QuerySyntaxException("Prefix " + prefix + " has already been declared");
        }
        this.prefixDeclarations.add(declarationAst);
    }
    
    public String getBaseUri() {
        return this.baseUri;
    }
    
    public List<PrefixDeclarationAst> getPrefixDeclaration() {
        return this.prefixDeclarations;
    }

    // --- Pattern creation ---

    protected boolean hasCurrentGroup() {
        return !this.groupStack.isEmpty();
    }

    protected List<PatternAst> currentGroup() {
        if (groupStack.isEmpty()) {
            throw new IllegalStateException("No current group. Did you call enterGroup() on enterGroupGraphPattern?");
        }
        return groupStack.peek();
    }

    /**
     * Asserts that no {@code TriplesBlock} (BGP) is currently open.
     *
     * @throws IllegalStateException if the BGP stack is not empty
     */
    protected void ensureNoOpenBgp() {
        if (!bgpStack.isEmpty()) {
            throw new IllegalStateException(
                    "exitGroup() called while a TriplesBlock/BGP is still open" +
                            " (open bgpStack depth=" + bgpStack.size() + ")");
        }
    }


    /**
     * Signals the start of a {@code GroupOrUnionGraphPattern}.
     */
    public void enterUnion() {
        unionStack.push(new ArrayList<>());
    }

    /**
     * Collects the most recently closed {@link GroupGraphPatternAst} as the next
     * branch of the current {@code UNION}.
     */
    public void collectUnionBranch() {
        List<GroupGraphPatternAst> currentUnion = unionStack.peek();
        if (currentUnion == null) {
            return;
        }
        if (groupStack.isEmpty()) {
            return;
        }
        List<PatternAst> current = currentGroup();
        if (!current.isEmpty() && current.getLast() instanceof GroupGraphPatternAst g) {
            current.removeLast();
            currentUnion.add(g);
        }
    }

    /**
     * Finalises the current {@code GroupOrUnionGraphPattern} and adds its result
     * to the enclosing group.
     */
    public void exitUnion() {
        List<GroupGraphPatternAst> branches = unionStack.pop();

        if (branches.isEmpty()) {
            return;
        }

        if (branches.size() == 1) {
            // Single branch: no UNION keyword was present, add the group directly
            currentGroup().add(branches.getFirst());
            return;
        }

        // Two or more branches: fold left-associatively into binary UnionAst nodes
        PatternAst result = new UnionAst(branches.get(0), branches.get(1));
        for (int i = 2; i < branches.size(); i++) {
            result = new UnionAst(
                    new GroupGraphPatternAst(List.of(result)),
                    branches.get(i)
            );
        }

        currentGroup().add(result);
    }

    public void addFromGraph(IriAst graph) {
        this.datasetDefaultGraphs.add(graph);
    }

    public void addFromNamedGraph(IriAst graph) {
        this.datasetNamedGraphs.add(graph);
    }

    /**
     * Enter a TriplesBlock -> begin collecting triples for a BGP.
     */
    public void enterBgp() {
        bgpStack.push(new ArrayList<>());
    }

    /**
     * Exit a TriplesBlock -> finalize into BgpAst and attach it to the current group.
     * Empty triples blocks produce no pattern.
     */
    public void exitBgp() {
        List<TriplePatternAst> triples = bgpStack.pop();
        if (!triples.isEmpty()) {
            currentGroup().add(new BgpAst(List.copyOf(triples)));
        }
    }

    /**
     * Called when the parser enters a {@code whereClause}
     * The following {@link SparqlQueryAstBuilder#enterGroup()} for that clause must attach to the current {@link SparqlQueryAstBuilder.SelectFrame}
     * when one is active.
     */
    public void enterWhereClause() {
        if (hasCurrentSelect()) {
            selectWhereGroupFollows = true;
        }
    }

    /**
     * Enter a { ... } groupGraphPattern.
     */
    public void enterGroup() {
        groupStack.push(new ArrayList<>());
        if (selectWhereGroupFollows && hasCurrentSelect()) {
            selectWhereGroupDepths.push(groupStack.size());
            selectWhereGroupFollows = false;
        } else {
            selectWhereGroupFollows = false;
        }
    }

    /**
     * Exit a { ... } groupGraphPattern.
     * Pops the current group, wraps it in {@link GroupGraphPatternAst}. If we had entered OPTIONAL
     * or MINUS and the parent group depth matches the corresponding stack, wraps in the dedicated AST node and adds to parent;
     * otherwise adds the group to parent or sets as top-level WHERE.
     * Must not be called while a TriplesBlock is still open (no pending enterBgp without exitBgp).
     */
    public void exitGroup() {
        ensureNoOpenBgp();
        int depthBeforePop = groupStack.size();

        if (!selectWhereGroupDepths.isEmpty()
                && hasCurrentSelect()
                && depthBeforePop == selectWhereGroupDepths.peek()) {
            selectWhereGroupDepths.pop();
            List<PatternAst> popped = groupStack.pop();
            getCurrentSelectFrame().whereClause = new GroupGraphPatternAst(popped);
            return;
        }

        List<PatternAst> popped = groupStack.pop();
        GroupGraphPatternAst group = new GroupGraphPatternAst(popped);

        if (!optionalGroupDepths.isEmpty() && groupStack.size() == optionalGroupDepths.peek()) {
            optionalGroupDepths.pop();
            currentGroup().add(new OptionalAst(group));
        } else if (!minusGroupDepths.isEmpty() && groupStack.size() == minusGroupDepths.peek()) {
            minusGroupDepths.pop();
            currentGroup().add(new MinusAst(group));
        } else if (!existsGroupDepths.isEmpty() && groupStack.size() == existsGroupDepths.peek()) {
            existsGroupDepths.pop();
            capturedExistsStack.push(group);
        } else if (!serviceStack.isEmpty() && groupStack.size() == serviceStack.peek().groupDepth()) {
            ServiceEntry entry = serviceStack.pop();
            currentGroup().add(new ServiceAst(entry.endpoint(), entry.silent(), group));
        } else if (groupStack.isEmpty()) {
            if (hasCurrentSelect()) getCurrentSelectFrame().whereClause = group;
            else whereClause = group;
        } else {
            currentGroup().add(group);
        }
    }

    /**
     * Check current select stack
     */
    protected boolean hasCurrentSelect() {
        return !selectStack.isEmpty();
    }

    /**
     * Peek current select stack
     */
    protected SelectFrame getCurrentSelectFrame() {
        if (selectStack.isEmpty()) {
            throw new IllegalStateException("No Current SELECT frame");
        }
        return selectStack.peek();
    }

    /**
     * Add a triple pattern to the current BGP (TriplesBlock).
     * This must be called while inside a TriplesBlock.
     */
    public void addTriple(TermAst s, PathAst p, TermAst o) {
        if (bgpStack.isEmpty()) {
            throw new IllegalStateException("addTriple() called outside of TriplesBlock (BGP). " +
                    "Ensure you call enterBgp() on enterTriplesBlock.");
        }
        bgpStack.peek().add(new TriplePatternAst(s, p, o));
    }

    /**
     * Add a triple whose predicate is a single term (IRI, variable, etc.).
     */
    public void addTriple(TermAst s, TermAst p, TermAst o) {
        addTriple(s, new PredicatePathAst(p), o);
    }

    // --- Filters ---

    /**
     * Exits a Filter and adds it to the current group
     */
    public void addFilter(FilterAst filter) {
        if (this.hasCurrentGroup()) {
            this.currentGroup().add(filter);
        }
    }

    /**
     * Adds {@code BIND(expression AS ?var)} to the current group. The variable must not already be
     * visible from earlier patterns in the same group (SPARQL 1.1 scoping).
     */
    public void addBind(BindAst bind) {
        if (bind == null) {
            throw new IllegalArgumentException("bind is null");
        }
        if (!hasCurrentGroup()) {
            throw new IllegalStateException("addBind() called outside of a group graph pattern");
        }
        List<PatternAst> group = currentGroup();
        Set<String> visibleSoFar = new LinkedHashSet<>();
        for (PatternAst prior : group) {
            visibleSoFar.addAll(
                    variableScopeAnalyzer.collectVisibleVariables(new GroupGraphPatternAst(List.of(prior))));
        }
        String name = bind.variable().name();
        if (visibleSoFar.contains(name)) {
            throw new QueryValidationException(
                    "Variable ?" + name + " used in BIND is already declared in the same group graph pattern");
        }
        group.add(bind);
    }

    // --- Optional ---

    /**
     * Enter OPTIONAL scope. Records current group stack size so that when we exitGroup() and the stack
     * is back to that size, we wrap the popped group in {@link OptionalAst}.
     */
    public void enterOptional() {
        optionalGroupDepths.push(groupStack.size());
    }

    /**
     * Exit OPTIONAL scope. No-op: the optional content was already wrapped in {@link OptionalAst} in {@link SparqlQueryAstBuilder#exitGroup()}.
     */
    public void exitOptional() {
    }

    // --- Minus ---

    /**
     * Enter MINUS scope. Records current group stack size so that when we exitGroup() and the stack
     * is back to that size, we wrap the popped group in {@link MinusAst}.
     */
    public void enterMinus() {
        minusGroupDepths.push(groupStack.size());
    }

    /**
     * Exit MINUS scope. No-op: the MINUS content was already wrapped in {@link MinusAst} in {@link SparqlQueryAstBuilder#exitGroup()}.
     */
    public void exitMinus() {
        // No-op: the MINUS content was already wrapped in MinusAst in exitGroup().
    }

    // --- Service ---

    /**
     * Enter SERVICE scope.  Records the current group stack size, the endpoint term and the
     * {@code SILENT} flag so that when {@link SparqlQueryAstBuilder#exitGroup()} is called and the stack returns to
     * that size, the closed group is wrapped in a
     * {@link ServiceAst}.
     *
     * @param endpoint the remote endpoint (IRI or variable)
     * @param silent   {@code true} when the {@code SILENT} keyword was present
     */
    public void enterService(TermAst endpoint, boolean silent) {
        serviceStack.push(new ServiceEntry(groupStack.size(), endpoint, silent));
    }

    /**
     * Exit SERVICE scope.  No-op: the service body was already wrapped in
     * {@link ServiceAst} in {@link SparqlQueryAstBuilder#exitGroup()}.
     */
    public void exitService() {
    }


    /**
     * Enter EXISTS scope. Records current group stack size so that when we exitGroup() and the stack
     * is back to that size.
     */
    public void enterExistsFunc() {
        existsGroupDepths.push(groupStack.size());
    }

    /**
     * Enter NOT EXISTS scope. Same mechanism as EXISTS.
     */
    public void enterNotExistsFunc() {
        existsGroupDepths.push(groupStack.size());
    }

    /**
     * Pops the captured GroupGraphPattern from the last closed EXISTS/NOT EXISTS block.
     */
    public GroupGraphPatternAst popCapturedExistsPattern() {
        return capturedExistsStack.pollFirst();
    }


    // --- Creation Term helpers ---

    /**
     * Variable token text can be "?s" or "$s" depending on grammar.
     */
    public TermAst var(String tokenText) {
        return terms.var(tokenText);
    }

    /**
     * IRI term as raw text:
     * <ul>
     *   <li>{@code <http://...>}</li>
     *   <li>{@code foaf:Person}</li>
     *   <li>{@code a}</li>
     * </ul>
     */
    public TermAst iri(String raw) {
        return terms.iri(raw);
    }

    /**
     * Literal term.
     * - lexical should be the literal lexical form (often including quotes at this stage)
     * - lang without '@' (e.g., "fr"), or null
     * - datatype as IRI/QName text (e.g., "xsd:integer"), or null
     */
    public TermAst literal(String lexical, String lang, String datatype) {
        return terms.literal(lexical, lang, datatype);
    }



    // ---- term helpers ----

    public TermAst termFromVerb(SparqlParser.VerbContext ctx) {
        return terms.termFromVerb(ctx);
    }

    public TermAst termFromVarOrTerm(SparqlParser.VarOrTermContext ctx) {
        return terms.termFromVarOrTerm(ctx);
    }

    public TermAst termFromVarOrIriRef(SparqlParser.VarOrIriContext ctx) {
        return terms.termFromVarOrIriRef(ctx);
    }

    public List<TermAst> termListFromObjectList(SparqlParser.ObjectListContext ctx) {
        return terms.termListFromObjectList(ctx, this::termFromObject);
    }

    public TermAst termFromObject(SparqlParser.Object_Context ctx) {
        // object_ : graphNode
        return termFromGraphNode(ctx.graphNode());
    }

    public TermAst termFromGraphNode(SparqlParser.GraphNodeContext ctx) {
        if (ctx.varOrTerm() != null) return termFromVarOrTerm(ctx.varOrTerm());
        if (ctx.triplesNode() != null) {
            // MVP: pas encore supporté ( [ ... ] ou ( ... ) )
            return this.iri(ctx.triplesNode().getText());
        }

        return this.iri(ctx.getText());
    }

    public TermAst termFromRdfLiteral(SparqlParser.RdfLiteralContext ctx) {
        return terms.termFromRdfLiteral(ctx);
    }

    public TermAst termFromVar(SparqlParser.Var_Context ctx) {
        return terms.termFromVar(ctx);
    }

    public TermAst termFromBooleanLiteral(SparqlParser.BooleanLiteralContext ctx) {
        return terms.termFromBooleanLiteral(ctx);
    }

    public TermAst termFromIriRef(SparqlParser.IriRefContext ctx) {
        return terms.termFromIriRef(ctx);
    }

    public TermAst termFromNumericLiteral(SparqlParser.NumericLiteralContext ctx) {
        return terms.termFromNumericLiteral(ctx);
    }

    public TermAst termFromBlankNode(SparqlParser.BlankNodeContext ctx) {
        String label = ctx.getText();
        blankNodeLabels.add(label);
        return this.iri(label);
    }

    /**
     * One {@code groupCondition}&nbsp;:&nbsp;{@code builtInCall | functionCall | ‘(‘ expression (‘AS’ var_)? ‘)’ | var_}.
     * <p>La forme {@code (expr AS ?v)} est résolue comme l’expression de regroupement (le nom optionnel rejoint la
     * spec en étant porté par la projection SELECT&nbsp;; l’AST minimal ne le duplique pas ici).
     */
    public TermAst termFromGroupCondition(SparqlParser.GroupConditionContext ctx) {
        return expressions.termFromGroupCondition(ctx);
    }

    public TermAst termFromConstraint(SparqlParser.ConstraintContext ctx) {
        return expressions.termFromConstraint(ctx);
    }

    public TermAst termFromExpression(SparqlParser.ExpressionContext ctx) {
        return expressions.termFromExpression(ctx);
    }

    public TermAst termFromBrackettedExpression(SparqlParser.BrackettedExpressionContext ctx) {
        return expressions.termFromBrackettedExpression(ctx);
    }

    /**
     * Predicate as a SPARQL 1.1 property path.
     */
    public PathAst pathFromVerbPath(SparqlParser.VerbPathContext ctx) {
        return paths.pathFromVerbPath(ctx);
    }

    /**
     * Creates a fresh internal blank node label for expanded BGP triples.
     */
    public TermAst newAnonymousBlankNode() {
        String label;
        do {
            label = GENERATED_BLANK_NODE_PREFIX + anonymousBlankNodeCounter++;
        } while (!blankNodeLabels.add(label));
        return iri(label);
    }

    /**
     * Expands a {@code propertyListPathNotEmpty} into triple patterns for the given subject.
     */
    public void addTriplesFromPropertyListPath(
            TermAst subject,
            SparqlParser.PropertyListPathNotEmptyContext propertyList) {
        var verbPaths = propertyList.verbPath();
        var verbSimples = propertyList.verbSimple();
        var objectLists = propertyList.objectListPath();

        int verbPathIdx = 0;
        int verbSimpleIdx = 0;

        for (SparqlParser.ObjectListPathContext objectList : objectLists) {
            PathAst predicate = predicateFromPropertyListPath(
                    verbPaths, verbSimples, verbPathIdx, verbSimpleIdx);
            if (verbPathIdx < verbPaths.size()
                    && (verbSimpleIdx >= verbSimples.size()
                    || verbPaths.get(verbPathIdx).getStart().getTokenIndex()
                    < verbSimples.get(verbSimpleIdx).getStart().getTokenIndex())) {
                verbPathIdx++;
            } else {
                verbSimpleIdx++;
            }

            for (TermAst object : termListFromObjectListPath(objectList)) {
                addTriple(subject, predicate, object);
            }
        }
    }

    private PathAst predicateFromPropertyListPath(
            List<SparqlParser.VerbPathContext> verbPaths,
            List<SparqlParser.VerbSimpleContext> verbSimples,
            int verbPathIdx,
            int verbSimpleIdx) {
        boolean useVerbPath = verbPathIdx < verbPaths.size()
                && (verbSimpleIdx >= verbSimples.size()
                || verbPaths.get(verbPathIdx).getStart().getTokenIndex()
                < verbSimples.get(verbSimpleIdx).getStart().getTokenIndex());
        if (useVerbPath) {
            return pathFromVerbPath(verbPaths.get(verbPathIdx));
        }
        return new PredicatePathAst(terms.termFromVerbSimple(verbSimples.get(verbSimpleIdx)));
    }

    /**
     * Builds triple patterns for a {@code triplesNodePath} subject and returns its head term.
     */
    public TermAst subjectFromTriplesNodePath(SparqlParser.TriplesNodePathContext ctx) {
        if (ctx.blankNodePropertyListPath() != null) {
            return subjectFromBlankNodePropertyListPath(ctx.blankNodePropertyListPath());
        }
        if (ctx.collectionPath() != null) {
            return subjectFromCollectionPath(ctx.collectionPath());
        }
        throw new QueryEvaluationException("Unexpected triples node path: " + ctx.getText());
    }

    private TermAst subjectFromBlankNodePropertyListPath(
            SparqlParser.BlankNodePropertyListPathContext ctx) {
        TermAst blankNode = newAnonymousBlankNode();
        if (ctx.propertyListPathNotEmpty() != null) {
            addTriplesFromPropertyListPath(blankNode, ctx.propertyListPathNotEmpty());
        }
        return blankNode;
    }

    private TermAst subjectFromCollectionPath(SparqlParser.CollectionPathContext ctx) {
        List<SparqlParser.GraphNodePathContext> nodes = ctx.graphNodePath();
        if (nodes.isEmpty()) {
            throw new QueryEvaluationException("Empty RDF collection in triple pattern");
        }

        TermAst head = newAnonymousBlankNode();
        TermAst current = head;
        for (int i = 0; i < nodes.size(); i++) {
            addTriple(current, rdfTerm(RDF.first), termFromGraphNodePath(nodes.get(i)));
            if (i == nodes.size() - 1) {
                addTriple(current, rdfTerm(RDF.rest), rdfTerm(RDF.nil));
            } else {
                TermAst next = newAnonymousBlankNode();
                addTriple(current, rdfTerm(RDF.rest), next);
                current = next;
            }
        }
        return head;
    }

    /**
     * Graph node inside a property-path triple (variable/term, blank node property list, or collection).
     */
    public TermAst termFromGraphNodePath(SparqlParser.GraphNodePathContext ctx) {
        if (ctx.varOrTerm() != null) {
            return termFromVarOrTerm(ctx.varOrTerm());
        }
        if (ctx.triplesNodePath() != null) {
            return subjectFromTriplesNodePath(ctx.triplesNodePath());
        }
        throw new QueryEvaluationException("Unexpected graph node path: " + ctx.getText());
    }

    private TermAst rdfTerm(RDF term) {
        return new IriAst("<" + term.getIRI().stringValue() + ">");
    }

    /**
     * List of objects inside a property path triple.
     */
    public List<TermAst> termListFromObjectListPath(SparqlParser.ObjectListPathContext ctx) {
        List<TermAst> out = new ArrayList<>();
        for (var objPath : ctx.objectPath()) {
            out.add(termFromGraphNodePath(objPath.graphNodePath()));
        }
        return out;
    }

    public GraphRefAst graphRefFromGraphOrDefault(SparqlParser.GraphOrDefaultContext ctx) {
        if (ctx.DEFAULT() != null) {
            return GraphRefAsts.defaultGraph();
        }
        if(ctx.iriRef() != null) {
            IriAst graphIri = (IriAst) termFromIriRef(ctx.iriRef());
            return GraphRefAsts.graph(graphIri);
        }
        throw new QueryEvaluationException("Unexpected value for Graph reference or default " + ctx.getText());
    }

    public GraphRefAst graphRefFromGraphRef(SparqlParser.GraphRefContext ctx) {
        if(ctx.iriRef() != null) {
            IriAst graphIri = (IriAst) termFromIriRef(ctx.iriRef());
            return GraphRefAsts.graph(graphIri);
        }
        throw new QueryEvaluationException("Unexpected value for Graph reference " + ctx.getText());
    }

    public GraphRefAst graphRefFromGraphRefAll(SparqlParser.GraphRefAllContext ctx) {
        if (ctx.DEFAULT() != null) {
            return GraphRefAsts.defaultGraph();
        }
        if(ctx.NAMED() != null) {
            return GraphRefAsts.named();
        }
        if(ctx.ALL() != null) {
            return GraphRefAsts.all();
        }
        if(ctx.graphRef() != null) {
            return graphRefFromGraphRef(ctx.graphRef());
        }
        throw new QueryEvaluationException("Unexpected value for Graph reference or default or named or all " + ctx.getText());
    }

    /**
     * Per-SELECT frame used to support nested SELECT subqueries.
     */
    protected static final class SelectFrame {
        protected GroupGraphPatternAst whereClause;
        protected ProjectionAst projection = ProjectionAsts.selectAll();
        protected boolean distinct;
        protected boolean reduced;
        protected Long limit;
        protected Long offset;
        protected GroupByAst groupBy = new GroupByAst(List.of());
        protected final List<OrderConditionAst> orderConditions = new ArrayList<>();
        protected final List<TermAst> havingConditions = new ArrayList<>();
    }
}
