package fr.inria.corese.core.next.data.impl.io.parser.trig;

import fr.inria.corese.core.next.data.api.model.Model;
import fr.inria.corese.core.next.data.api.factory.ValueFactory;
import fr.inria.corese.core.next.data.api.io.format.RDFFormat;
import fr.inria.corese.core.next.data.api.support.io.parser.AbstractRDFParser;
import fr.inria.corese.core.next.data.api.io.option.IOOptions;
import fr.inria.corese.core.next.data.api.exception.ParsingException;
import fr.inria.corese.core.next.generated.antlr.TriGLexer;
import org.antlr.v4.runtime.BaseErrorListener;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.RecognitionException;
import org.antlr.v4.runtime.Recognizer;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * A parser for the TriG format based on ANTLR4.
 * It uses an ANTLR grammar to tokenize and parse TriG documents,
 * then a listener to build the RDF model.
 */
public class TriGParser extends AbstractRDFParser {

    /**
     * Constructor for the ANTLRTrigParser.
     *
     * @param model   The RDF model to be populated.
     * @param factory The value factory for creating RDF resources.
     */
    public TriGParser(Model model, ValueFactory factory) {
        this(model, factory, new TriGParserOptions.Builder().build());
    }

    /**
     * Constructor for the ANTLRTrigParser with configuration options.
     *
     * @param model   The RDF model to be populated.
     * @param factory The value factory for creating RDF resources.
     * @param config  Configuration options for parsing.
     */
    public TriGParser(Model model, ValueFactory factory, IOOptions config) {
        super(model, factory, config);
    }

    @Override
    public RDFFormat getRDFFormat() {
        return RDFFormat.TRIG;
    }

    @Override
    public void parse(InputStream in, String baseURI) throws ParsingException {
        parse(new InputStreamReader(in, StandardCharsets.UTF_8), baseURI);
    }

    /**
     * Parses TriG data from a {@link Reader} using ANTLR4.
     *
     * @param reader  The {@link Reader} to read the RDF data.
     * @param baseURI The base URI.
     * @throws ParsingException if a parsing or I/O error occurs.
     */
    @Override
    public void parse(Reader reader, String baseURI) throws ParsingException {
        try {
            CharStream charStream = CharStreams.fromReader(reader);
            TriGLexer triGLexer = new TriGLexer(charStream);

            TrigErrorListener trigErrorListener = new TrigErrorListener();
            triGLexer.removeErrorListeners();
            triGLexer.addErrorListener(trigErrorListener);

            CommonTokenStream tokens = new CommonTokenStream(triGLexer);
            fr.inria.corese.core.next.generated.antlr.TriGParser triGParser = new fr.inria.corese.core.next.generated.antlr.TriGParser(tokens);


            triGParser.removeErrorListeners();
            triGParser.addErrorListener(trigErrorListener);

            ParseTreeWalker walker = new ParseTreeWalker();
            ParseTree tree = triGParser.trigDoc();

            if (trigErrorListener.hasErrors()) {
                throw new ParsingException("Syntax error in TriG document: " + trigErrorListener.getErrorMessage());
            }
            IOOptions optionsWithBaseURI = new TriGParserOptions.Builder()
                    .baseIRI(baseURI)
                    .build();
            TriGListener listener = new TriGListener(getModel(), getValueFactory(), optionsWithBaseURI);
            walker.walk(listener, tree);

        } catch (ParsingException e) {
            throw e;
        } catch (IOException e) {
            throw new ParsingException("Failed to parse TriG RDF: " + e.getMessage(), e);
        } catch (Exception e) {
            throw new ParsingException("Unexpected error during TriG parsing: " + e.getMessage(), e);
        }
    }


    /**
     * A custom error listener to collect errors from the lexer and parser.
     */
    private static class TrigErrorListener extends BaseErrorListener {
        private final List<String> errors = new ArrayList<>();

        /**
         * Records syntax errors generated by ANTLR.
         *
         * @param recognizer         The recognizer that detected the error.
         * @param offendingSymbol    The symbol that caused the error.
         * @param line               The line number where the error occurred.
         * @param charPositionInLine The character position on the line.
         * @param msg                The error message.
         * @param e                  The recognition exception.
         */
        @Override
        public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol,
                                int line, int charPositionInLine, String msg, RecognitionException e) {
            if (msg != null && (msg.contains("token recognition error") || msg.contains("mismatched input"))
                    && offendingSymbol instanceof Token token) {
                String tokenText = token.getText();
                if (msg.contains("token recognition error") && tokenText != null && tokenText.contains("\"")) {
                    msg = "Invalid string literal - possibly unterminated or contains invalid escape sequence: " + msg;
                }
            }

            String error = "line " + line + ":" + charPositionInLine + " " + msg;
            errors.add(error);
        }

        /**
         * Checks if parsing errors have been found.
         *
         * @return `true` if the error list is not empty, otherwise `false`.
         */
        public boolean hasErrors() {
            return !errors.isEmpty();
        }

        /**
         * Returns a formatted error message containing all found errors.
         *
         * @return A {@link String} containing the error messages.
         */
        public String getErrorMessage() {
            return String.join("; ", errors);
        }
    }
}
