package fr.inria.corese.core.load;

import com.fasterxml.jackson.databind.JsonMappingException;
import com.github.jsonldjava.core.JsonLdProcessor;
import com.github.jsonldjava.core.JsonLdTripleCallback;
import com.github.jsonldjava.core.RDFDataset;
import com.github.jsonldjava.utils.JsonUtils;
import fr.com.hp.hpl.jena.rdf.arp.ALiteral;
import fr.com.hp.hpl.jena.rdf.arp.ARP;
import fr.com.hp.hpl.jena.rdf.arp.AResource;
import fr.com.hp.hpl.jena.rdf.arp.StatementHandler;
import fr.inria.corese.core.sparql.triple.javacc1.JavaccParseException;
import fr.inria.corese.core.sparql.triple.javacc1.SparqlCorese;
import fr.inria.corese.core.sparql.triple.parser.ASTQuery;
import fr.inria.corese.core.sparql.triple.parser.ParserHandler;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xml.sax.SAXException;

import java.io.*;
import java.util.List;

import static org.junit.Assert.*;

/**
 * This file contains minimal tests for the parsing of RDF files as done in Corese. The triples are NOT loaded into a graph of equivalent data structure.
 */
public class ParserTest {

    private static final Logger logger = LoggerFactory.getLogger(ParserTest.class);


    @Test
    public void parseTurtle() throws IOException, JavaccParseException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/rdfs.2014.ttl";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        // Create SparqlCorese object, parser generated by JavaCC
        SparqlCorese turtleParser = new SparqlCorese(fileInputStream);
        turtleParser.setHandler(new ParserHandler()); // What is ParserHandler?
        ASTQuery ast = ASTQuery.create();
        ast.getNSM().setBase("http://example.org/");
        turtleParser.setASTQuery(ast);
        ASTQuery loadedQuery = turtleParser.load(); // What is the difference between load and parse?

        fileInputStream.close();

        assertNotNull(loadedQuery);
        assertEquals(87, loadedQuery.getTripleList().size());
    }


    @Test
    public void parseTurtleWithStressCharacters() throws IOException, JavaccParseException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/stressCharacters.ttl";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        // Create SparqlCorese object, parser generated by JavaCC
        SparqlCorese turtleParser = new SparqlCorese(fileInputStream);
        turtleParser.setHandler(new ParserHandler()); // What is ParserHandler?
        ASTQuery ast = ASTQuery.create();
        ast.getNSM().setBase("http://example.org/");
        turtleParser.setASTQuery(ast);
        ASTQuery loadedQuery = turtleParser.load(); // What is the difference between load and parse?

        fileInputStream.close();

        assertNotNull(loadedQuery);
        assertEquals(5, loadedQuery.getTripleList().size());
    }


    @Test
    public void parseIncorrectTurtle() throws IOException, JavaccParseException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/incorrect.ttl";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        // Create SparqlCorese object, parser generated by JavaCC
        SparqlCorese turtleParser = new SparqlCorese(fileInputStream);
        turtleParser.setHandler(new ParserHandler()); // What is ParserHandler?
        ASTQuery ast = ASTQuery.create();
        ast.getNSM().setBase("http://example.org/");
        turtleParser.setASTQuery(ast);

        assertThrows(JavaccParseException.class, () -> {
            turtleParser.load();
        });

        fileInputStream.close();
    }

    @Test
    public void parseNTriples() throws IOException, JavaccParseException {
        // Get file stream for ntriples file
        String filePathString = "src/test/resources/data-test/rdfs.2014.nt";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        // Create SparqlCorese object, parser generated by JavaCC
        SparqlCorese turtleParser = new SparqlCorese(fileInputStream);
        turtleParser.setHandler(new ParserHandler()); // What is ParserHandler?
        ASTQuery ast = ASTQuery.create();
        ast.getNSM().setBase("http://example.org/");
        turtleParser.setASTQuery(ast);
        ASTQuery loadedQuery = turtleParser.load(); // What is the difference between load and parse?

        fileInputStream.close();

        assertNotNull(loadedQuery);
        assertEquals(87, loadedQuery.getTripleList().size());
    }


    @Test
    public void parseNTriplesWithStressCharacters() throws IOException, JavaccParseException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/stressCharacters.nt";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        // Create SparqlCorese object, parser generated by JavaCC
        SparqlCorese turtleParser = new SparqlCorese(fileInputStream);
        turtleParser.setHandler(new ParserHandler()); // What is ParserHandler?
        ASTQuery ast = ASTQuery.create();
        ast.getNSM().setBase("http://example.org/");
        turtleParser.setASTQuery(ast);
        ASTQuery loadedQuery = turtleParser.load(); // What is the difference between load and parse?

        fileInputStream.close();

        assertNotNull(loadedQuery);
        assertEquals(5, loadedQuery.getTripleList().size());
    }


    @Test
    public void parseIncorrectNtriples() throws IOException, JavaccParseException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/incorrect.nt";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        // Create SparqlCorese object, parser generated by JavaCC
        SparqlCorese turtleParser = new SparqlCorese(fileInputStream);
        turtleParser.setHandler(new ParserHandler()); // What is ParserHandler?
        ASTQuery ast = ASTQuery.create();
        ast.getNSM().setBase("http://example.org/");
        turtleParser.setASTQuery(ast);

        assertThrows(JavaccParseException.class, () -> {
            turtleParser.load();
        });

        fileInputStream.close();
    }

    @Test
    public void parseTrig() throws IOException, JavaccParseException {
        // Get file stream for trig file
        String filePathString = "src/test/resources/data-test/rdfAndRDFS.trig";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        // Create SparqlCorese object, parser generated by JavaCC
        SparqlCorese turtleParser = new SparqlCorese(fileInputStream);
        turtleParser.setHandler(new ParserHandler()); // What is ParserHandler?
        ASTQuery ast = ASTQuery.create();
        ast.getNSM().setBase("http://example.org/");
        turtleParser.setASTQuery(ast);
        ASTQuery loadedQuery = turtleParser.load(); // What is the difference between load and parse?

        fileInputStream.close();

        assertNotNull(loadedQuery);
        assertEquals(214, loadedQuery.getTripleList().size());
    }

    @Test
    public void parseIncorrectTrig() throws IOException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/incorrect.trig";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        // Create SparqlCorese object, parser generated by JavaCC
        SparqlCorese turtleParser = new SparqlCorese(fileInputStream);
        turtleParser.setHandler(new ParserHandler()); // What is ParserHandler?
        ASTQuery ast = ASTQuery.create();
        ast.getNSM().setBase("http://example.org/");
        turtleParser.setASTQuery(ast);

        assertThrows(Error.class, () -> {
            turtleParser.load();
        });

        fileInputStream.close();
    }


    @Test
    public void parseTrigWithStressCharacters() throws IOException, JavaccParseException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/stressCharacters.trig";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        // Create SparqlCorese object, parser generated by JavaCC
        SparqlCorese turtleParser = new SparqlCorese(fileInputStream);
        turtleParser.setHandler(new ParserHandler()); // What is ParserHandler?
        ASTQuery ast = ASTQuery.create();
        ast.getNSM().setBase("http://example.org/");
        turtleParser.setASTQuery(ast);
        ASTQuery loadedQuery = turtleParser.load(); // What is the difference between load and parse?

        fileInputStream.close();

        assertNotNull(loadedQuery);
        assertEquals(5, loadedQuery.getTripleList().size());
    }

    @Test
    public void parseXML() throws IOException, SAXException {
        // Get file stream for RDFXML file
        String filePathString = "src/test/resources/data-test/rdfs.2014.rdf";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);
        final int[] tripleCount = {0};

        ARP arp = new ARP();
        arp.setStatementHandler(new StatementHandler() {
            @Override
            public void statement(AResource subj, AResource pred, AResource obj) {
                 tripleCount[0]++;
            }

            @Override
            public void statement(AResource subj, AResource pred, ALiteral lit) {
                tripleCount[0]++;
            }
        });
        arp.load(fileInputStream, "http://example.org/");

        fileInputStream.close();

        assertEquals(87, tripleCount[0]);
    }

    /**
     * Corese parser fails on literal containing unicode characters
     */
    @Test
    public void parseXMLWithStressCharacters() throws IOException, SAXException {
        /*
        // Get file stream for RDFXML file
        String filePathString = "src/test/resources/data-test/stressCharacters.rdf";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);
        final int[] tripleCount = {0};

        ARP arp = new ARP();
        arp.setStatementHandler(new StatementHandler() {
            @Override
            public void statement(AResource subj, AResource pred, AResource obj) {
                tripleCount[0]++;
            }

            @Override
            public void statement(AResource subj, AResource pred, ALiteral lit) {
                tripleCount[0]++;
            }
        });
        arp.load(fileInputStream, "http://example.org/");

        fileInputStream.close();

        assertEquals(5, tripleCount[0]);
        */
    }

    @Test
    public void parseIncorrectXML() throws IOException, SAXException {
        // Get file stream for RDFXML file
        String filePathString = "src/test/resources/data-test/incorrect.rdf";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        ARP arp = new ARP();
        arp.setStatementHandler(new StatementHandler() {
            @Override
            public void statement(AResource subj, AResource pred, AResource obj) {
            }

            @Override
            public void statement(AResource subj, AResource pred, ALiteral lit) {
            }
        });

        assertThrows(SAXException.class, () -> arp.load(fileInputStream, "http://example.org/"));

        fileInputStream.close();
    }

    /**
     * Parsing of JSON LD files is entirely handled by external parser
     */
    @Test
    public void parseJSONLD() throws IOException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/rdfs.2014.jsonld";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);
        Reader targetReader = new InputStreamReader(fileInputStream);
        final int[] tripleCount = {0};

        // Calling JSON parser
        Object jsonObject = JsonUtils.fromReader(targetReader);
        Object jsonLdRDFObject = JsonLdProcessor.toRDF(jsonObject, new JsonLdTripleCallback() {
            @Override
            public Object call(RDFDataset rdfDataset) {
                for (String graphName : rdfDataset.graphNames()) {
                    List<RDFDataset.Quad> quadList = rdfDataset.getQuads(graphName);
                    for (RDFDataset.Quad quad : quadList) {
                        tripleCount[0]++;
                    }
                }
                return jsonObject;
            }
        }); // Should have a JsonLdCallback as second argument to load the triples into a Graph/Model

        assertNotNull(jsonLdRDFObject);
        assertEquals(87, tripleCount[0]);
    }

    /**
     * Parsing of JSON LD files is entirely handled by external parser
     */
    @Test
    public void parseJSONLDWithStressCharacters() throws IOException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/stressCharacters.jsonld";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);
        Reader targetReader = new InputStreamReader(fileInputStream);
        final int[] tripleCount = {0};

        // Calling JSON parser
        Object jsonObject = JsonUtils.fromReader(targetReader);
        Object jsonLdRDFObject = JsonLdProcessor.toRDF(jsonObject, new JsonLdTripleCallback() {
            @Override
            public Object call(RDFDataset rdfDataset) {
                for (String graphName : rdfDataset.graphNames()) {
                    List<RDFDataset.Quad> quadList = rdfDataset.getQuads(graphName);
                    for (RDFDataset.Quad quad : quadList) {
                        tripleCount[0]++;
                    }
                }
                return jsonObject;
            }
        }); // Should have a JsonLdCallback as second argument to load the triples into a Graph/Model

        assertNotNull(jsonLdRDFObject);
        assertEquals(5, tripleCount[0]);
    }

    /**
     * Parsing of JSON LD files is entirely handled by external parser
     */
    @Test
    public void parseIncorrectJSONLD() throws IOException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/incorrect.jsonld";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);
        Reader targetReader = new InputStreamReader(fileInputStream);

        // Calling JSON parser
        assertThrows(JsonMappingException.class, () -> JsonUtils.fromReader(targetReader));
    }
}
