package fr.inria.corese.core.load;

import fr.inria.corese.core.sparql.triple.javacc1.JavaccParseException;
import fr.inria.corese.core.sparql.triple.javacc1.SparqlCorese;
import fr.inria.corese.core.sparql.triple.parser.ASTQuery;
import fr.inria.corese.core.sparql.triple.parser.ParserHandler;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

import static org.junit.Assert.assertNotNull;

public class ParserTurtleTest {

    private static final Logger logger = LoggerFactory.getLogger(ParserTurtleTest.class);

    @Test
    public void parseTurtle() throws FileNotFoundException, JavaccParseException {
        // Get file stream for turtle file
        String filePathString = "src/test/resources/data-test/rdfs.2014.ttl";
        File file = new File(filePathString);
        FileInputStream fileInputStream = new FileInputStream(file);

        // Create SparqlCorese object, parser generated by JavaCC
        SparqlCorese turtleParser = new SparqlCorese(fileInputStream);
        turtleParser.setHandler(new ParserHandler());
        ASTQuery ast = ASTQuery.create();
        ast.getNSM().setBase("http://example.org/");
        turtleParser.setASTQuery(ast);
        ASTQuery loadedQuery = turtleParser.load(); // What is the difference between load and parse?
        logger.debug("loadedQuery = {}", loadedQuery);

        assertNotNull(loadedQuery);
    }
}
