name: Continuous Integration process
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: maven build
        run: |
          mamba env update -f conda-env/corese-core.yaml
          conda activate corese-core
          mvn clean install -DskipTests
        shell: bash -l {0}

      - run: echo "This job's status is ${{ job.status }}."
