name: Continuous Integration process
run-name: ${{ github.actor }} has launched CI process on ${{ github.ref_name }}
on:
  push:
    branches:
#      - "main"
#      - "develop"
       - "do_not_execute"
  pull_request:
    branches:
#      - "main"
#      - "develop"
       - "do_not_execute"
jobs:
  Continuous-Integration-Actions:
    runs-on: self-hosted
    steps:
      - name: Checkout of head
        id: ci-maven-build-checkout
        uses: actions/checkout@v4

      - name: gradle build
        id: ci-gradle-build
        run: |
          mamba env update --prune -f conda-env/corese-core.yaml
          conda activate corese-core
          ./gradlew clean publishToMavenLocal
        shell: bash -l {0}

      - name: Final Step
        id: ci-final-step
        run: |
          echo "This job's status is ${{ job.status }}."
        shell: bash -l {0}
