name: Continuous Integration process
run-name: ${{ github.actor }} has launched CI process on ${{ github.ref_name }}
on:
  push:
    branches:
#      - "main"
#      - "develop"
      - "feature/github-actions-gradle"
  pull_request:
    branches:
#      - "main"
#      - "develop"
      - "do_not_execute"

jobs:
  Continuous-Integration-Actions:
    runs-on: self-hosted
    # env:
    #   JAVA_VERSION: 22

    steps:
      - name: Checkout of head
        id: ci-sources-checkout
        uses: actions/checkout@v4

      - name: Set up JDK 22
        id: ci-java-setup
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: 'temurin'
      - name: Gradle build
        id: ci-gradle-build
        run: ./gradlew clean publishToMavenLocal
        shell: bash -l {0}

      - name: Final Step
        id: ci-final-step
        run: |
          echo "This job's status is ${{ job.status }}."
#        shell: bash -l {0}
