name: Continuous Integration process
run-name: ${{ github.actor }} has launched CI process on ${{ github.ref_name }}
on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/github-actions"
  pull_request:
    branches:
      - "main"
      - "develop"
jobs:
  Continuous-Integration-Actions:
    runs-on: self-hosted
    steps:
      - name: maven build
        run: |
          mamba env update -f conda-env/corese-core.yaml
          conda activate corese-core
          mvn clean install -DskipTests
        shell: bash -l {0}

      - run: echo "This job's status is ${{ job.status }}."
