name: Continuous Integration process without conda
run-name: ${{ github.actor }} has launched CI-noconda process on ${{ github.ref_name }}
on:
  push:
    branches:
      - "feature/github-actions"

jobs:
  Continuous-Integration-Actions:
    runs-on: self-hosted
    env:
        JAVA_VERSION: '22'

    steps:
      - name: Checkout of head
        id: ci-noconda-sources-checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{env.JAVA_VERSION}}
        id: ci-noconda-java-setup
        uses: actions/setup-java@v3
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: temurin
          cache: maven
      - name: Maven build
        id: ci-noconda-maven-build
        run: |
          mvn clean package
      - name: Final Step
        id: ci-noconda-final-step
        run: |
          echo "This job's status is ${{ job.status }}."
