name: Publish Dev Pre-release
run-name: ${{ github.actor }} triggered pre-release on ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag to run workflow on'
        required: true
  push:
    branches:
      - develop

jobs:
  prerelease-github:
    name: Build and Publish Pre-release
    runs-on: [self-hosted, corese-stack-ubuntu-24]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build project
        run: ./gradlew shadowJar

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date '+%d %B %Y, %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Publish single pre-release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar"
          tag: dev-prerelease
          name: "Development Pre-release"
          body: |
            🚧 This is the latest build from the `develop` branch.
            Not intended for production use.
            
            **Last Updated:** ${{ steps.timestamp.outputs.timestamp }}
            **Build Info:**
            - Branch: `${{ github.ref_name }}`
            - Commit: `${{ github.sha }}`
            - Build Time: `${{ steps.timestamp.outputs.timestamp }}`
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
