name: "Sphinx: Render docs"
run-name: ${{ github.actor }} has launched CI process on ${{ github.ref_name }}
on:
  push:
    branches:
      - "feature/retrieve_doc"  # TODO Should build from main branch
  pull_request:
    branches:
      - "develop"

permissions:
  contents: write

jobs:
  Continuous-Integration-Actions:
    runs-on: self-hosted

    env:
      PACKAGE_TOKEN: ${{ secrets.JLS_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: feature/retrieve_doc

    - name: Fetch tags
      run: git fetch --prune --unshallow --tags

    - name: Install dependencies
      run: |
        source /builds/miniconda3/etc/profile.d/conda.sh
        conda activate corese-core-documentation
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Build Sphinx documentation with multiversion
      run: |
        source /builds/miniconda3/etc/profile.d/conda.sh
        conda activate corese-core-documentation
        sphinx-multiversion docs/source build/html -D 'exhale_args.containmentFolder=${sourcedir}/java_api'
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
