name: "Sphinx: Render production docs"
run-name: ${{ github.actor }} has launched CI process on ${{ github.ref_name }}
on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  Continuous-Integration-Actions:
    runs-on: self-hosted

    env:
      PACKAGE_TOKEN: ${{ secrets.JLS_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Fetch tags
      run: git fetch --prune --unshallow --tags --force

<<<<<<< HEAD:.github/workflows/sphinx.yml
    - name: Install dependencies
      run: |
        source /builds/miniconda3/etc/profile.d/conda.sh
        conda env update -f ./conda-env/corese-core-documentation.yaml
        conda activate corese-core-documentation

=======
>>>>>>> a04ede39 (Prepare for release.):.github/workflows/sphinx-prod.yml
    - name: Build Sphinx documentation with multiversion
      run: |
        source /builds/miniconda3/etc/profile.d/conda.sh
        conda activate corese-core-documentation
        sphinx-multiversion docs/source build/html -D 'exhale_args.containmentFolder=${sourcedir}/java_api'
        chmod u+x docs/switcher_generator.sh
        ./docs/switcher_generator.sh build/html/switcher.json build/html/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
